# Generated by Django 4.2.19 on 2025-04-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='send_reminder',
            field=models.BooleanField(default=True),
        ),
    ]
